# Generated by Django 3.1 on 2021-02-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0003_auto_20210217_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='country_name',
            field=models.CharField(max_length=500),
        ),
    ]
