# Generated by Django 3.1 on 2021-02-17 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0004_auto_20210217_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='country_name',
            new_name='countries',
        ),
    ]
